---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: rhel-7.0

suites:
  - name: default
    run_list:
      - recipe[rhel-test]
    attributes: {
      rhel-test: {
        username: "<%= ENV['RHEL_USER'] %>",
        password: "<%= ENV['RHEL_PASS'] %>"
        }
      }
